; Configuración básica
upload_max_filesize = 20M
post_max_size = 20M
memory_limit = 256M
max_execution_time = 300
max_input_time = 300

; Configuración de sesión
session.cookie_secure = 1 ; Habilitar solo en HTTPS
session.cookie_httponly = 1

; Configuración de opcache (opcional para producción)
opcache.enable=1
opcache.memory_consumption=128
opcache.max_accelerated_files=4000
opcache.revalidate_freq=60

display_errors = Off
log_errors = On
error_log = /var/log/php_errors.log

realpath_cache_size = 4096k
